version: '3.9'

services:
  redis:
    image: redis:6.2
    healthcheck:
      test: "redis-cli ping"
      interval: 1s
      retries: 20
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: host
    volumes:
      - ${PWD}/redis_data:/data
